management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: security-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/client-credentials

server:
  port: 8080

application:
  oauth2-security:
    authenticated-path-matchers:
      - "/principal"
    identity-claim-label: clientId
