logging:
  level:
    de.springframework.monitoring.hystrix.consumer: INFO
    root: INFO

management:
  server:
    port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

server:
  port: 8080
