logging:
  level:
    de.springframework.monitoring.hystrix.producer: INFO
    root: INFO

spring:
  application:
    name: hystrix-producer-service

  datasource:
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 32769

  h2:
    console:
      enabled: true
      path: /h2-console

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8081
  servlet:
    context-path: /producer

eureka:
  client:
    enabled: true
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      cluster: HYSTRIX-CLUSTER

