version: '2'

services:
  app-backend:
    image: kgent/spring-boot-monitoring-consul-backend:0.0.1-SNAPSHOT
    container_name: 'petclinic-rest-backend'
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
    ports:
      - 8080:8080
    depends_on:
      - app-consul
      - app-postgresql

  app-consul:
    extends:
      file: consul.yml
      service: consul

  app-postgresql:
    extends:
      file: postgresql.yml
      service: postgresql

  app-prometheus:
    extends:
      file: monitoring.yml
      service: prometheus

  app-grafana:
    extends:
      file: monitoring.yml
      service: grafana
    depends_on:
      - app-prometheus
