version: '2'

services:
  consul:
    image: consul:1.6.2
    container_name: 'consul'
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0

  consul-config-loader:
    image: jhipster/consul-config-loader
    container_name: 'consul-config-loader'
    volumes:
      - ./config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
      - CONFIG_MODE=git
