version: '2'

services:
  app-consul:
    image: consul:1.6.2
    container_name: 'consul'
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0
