management:
  server:
    port: 8091

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgresql
    username: postgresql
    password:
  liquibase:
    enabled: true
  redis:
    host: redis
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

server:
  port: 8081
