logging:
  level:
    de.springframework.monitoring.resilience4j.producer: INFO
    root: INFO

management:
  server:
    port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.hbm2ddl.auto: none
      hibernate.format_sql: true
      hibernate.generate_statistics: false
  liquibase:
    enabled: true
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
