logging:
  level:
    root: INFO

spring:
  application:
    name: hystrix-eureka-server
  mvc:
    async:
      request-timeout: 35000     #Prometheus use long Polling

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 10
