version: '2'

services:
  postgresql:
    image: postgres:12.1
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
