logging:
  level:
    de.springframework.monitoring.hystrix.producer: INFO
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.hbm2ddl.auto: none
      hibernate.format_sql: true
      hibernate.generate_statistics: false
  liquibase:
    enabled: true

server:
  port: 8081
