logging:
  level:
    de.springframework.monitoring.hystrix.producer: INFO
    root: INFO

management:
  server:
    port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgresql
    username: postgresql
    password:
  liquibase:
    enabled: true
  redis:
    host: redis
    port: 6379

server:
  port: 8081
