logging:
  level:
    de.springframework.monitoring.hystrix.producer: INFO
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-init-sql: SELECT 1
  liquibase:
    enabled: true

server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
