management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: hystrix-producer-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari-Master
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.hbm2ddl.auto: validate
      hibernate.format_sql: false
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true

  liquibase:
    enabled: false
    change-log: classpath:config/liquibase/master.xml

server:
  servlet:
    context-path: /producer

eureka:
  client:
    enabled: true
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      cluster: HYSTRIX-CLUSTER
