management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: hystrix-producer-service
  mvc:
    async:
      request-timeout: 35000
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari-Master
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.hbm2ddl.auto: validate
      hibernate.format_sql: false
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true

  liquibase:
    enabled: false
    change-log: classpath:config/liquibase/master.xml

hystrix:
  threadpool:
    default:
      coreSize: 100   # Maximum number of concurrent requests when using thread pools (Default: 10)
      maxQueueSize: -1   # Maximum LinkedBlockingQueue size - -1 for using SynchronousQueue (Default: -1)
      queueSizeRejectionThreshold: 5   # Queue size rejection threshold (Default: 5)
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 3
      execution:
        isolation:
          strategy: THREAD   # strategy: SEMAPHORE, no thread pool but timeout handling stops to work
          thread:
            timeoutInMilliseconds: 4000

server:
  servlet:
    context-path: /producer

eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      cluster: HYSTRIX-CLUSTER
