{
 "title": "Hystrix Dashboard",
 "description": "Dashboard to monitor key metrics for Hystrix. The Hystrix metrics are published using Prometheus' simpleclient through this library https://github.com/soundcloud/prometheus-hystrix",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "group",
    "label": "Command Group",
    "query": "label_values(hystrix_execution_total{application=\"$application\"}, group)"
   },
   {
    "name": "command",
    "label": "Command Name",
    "query": "label_values(hystrix_execution_total{group=\"$group\", application=\"$application\"}, key)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hystrix_circuit_breaker_open{group=~\"$group\",key=~\"$command\"})== bool 0"
    }
   ]
  },
  {
   "title": "Open Circuitbreaker",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "hystrix_circuit_breaker_open{application=\"hystrix-consumer-service\",group=\"FeignPersonService\"} != 0",
     "legendFormat": "{{group}} ({{application}})"
    }
   ]
  },
  {
   "title": "Total Latency of 50%, 75%, 90%, 95%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hystrix_latency_total_seconds_bucket{application=\"$application\", group=\"$group\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(hystrix_latency_total_seconds_bucket{application=\"$application\", group=\"$group\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(hystrix_latency_total_seconds_bucket{application=\"$application\", group=\"$group\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(hystrix_latency_total_seconds_bucket{application=\"$application\", group=\"$group\"}[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  { "title": "Executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Executions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "hystrix_execution_terminal_total{application=\"hystrix-consumer-service\"}",
     "legendFormat": "{{key}} ({{group}})"
    }
   ]
  },
  {
   "title": "Latency  Execution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hystrix_latency_execution_seconds_sum{application=\"$application\", group=\"$group\"}[1m])/rate(hystrix_latency_execution_seconds_count{application=\"$application\", group=\"$group\"}[1m])",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Command Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Open Circuit Breakers Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_circuit_breaker_open{application=~\"$application\",group=~\"$group\"}",
     "legendFormat": "{{key}} ({{group}})"
    }
   ]
  },
  {
   "title": "Successes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{application=~\"$application\",group=~\"$group\",event=~\"success\"}",
     "legendFormat": "{{key}} ({{group}})"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{application=~\"$application\",group=~\"$group\",event=~\"failure\"}",
     "legendFormat": "{{key}} ({{group}})"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{application=~\"$application\",group=~\"$group\",event=~\"timeout\"}",
     "legendFormat": "{{key}} ({{group}})"
    }
   ]
  },
  {
   "title": "Fallback Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{application=~\"$application\",group=~\"$group\",event=~\"fallback_success\"}",
     "legendFormat": "{{key}} ({{group}})"
    }
   ]
  },
  {
   "title": "Fallback Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{application=~\"$application\",group=~\"$group\",event=~\"fallback_failure\"}",
     "legendFormat": "{{key}} ({{group}})"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{application=~\"$application\",group=~\"$group\",event=~\"cancelled\"}",
     "legendFormat": "{{key}} ({{group}})"
    }
   ]
  },
  {
   "title": "Threadpool Rejected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{application=~\"$application\",group=~\"$group\",event=~\"thread_pool_rejected\"}",
     "legendFormat": "{{key}} ({{group}})"
    }
   ]
  },
  { "title": "Threadpools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Thread Pool / Active Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_threadpool_threads_active_current_count{application=~\"$application\",key=~\"$group\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Thread Pool / Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_threadpool_queue_current_size{application=\"$application\",key=\"$group\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Thread Pool / Rejected Threshold Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_threadpool_queue_rejection_threshold_size{application=~\"$application\",key=~\"$group\"}",
     "legendFormat": "{{key}}"
    }
   ]
  }
 ]
}