spring:
  cloud:
    consul:
      discovery:
        tags:
          - prod

  datasource:
    url: jdbc:postgresql://localhost:5432/petclinic
    username: petclinic
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-init-sql: SELECT 1

application:
