spring:
  cloud:
    consul:
      discovery:
        tags:
          - prod

  datasource:
    url: jdbc:postgresql://localhost:32768/petclinic
    username: petclinic
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.hbm2ddl.auto: validate
      hibernate.format_sql: true
      hibernate.generate_statistics: false

application:
