spring:
  cloud:
    consul:
      discovery:
        tags:
          - dev

  datasource:
    url: jdbc:postgresql://localhost:5432/petclinic
    username: petclinic
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.format_sql: true
      hibernate.generate_statistics: false

  flyway:
    enabled: false

server:
  port: 8085

application:
