version: '2'

services:
  mongodb:
    image: mongo:4.0.13
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
