spring:
  application:
    name: resilience4j-consumer-service
  thymeleaf:
    cache: false

management:
  health:
    diskspace:
      enabled: false
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        resilience4j.circuitbreaker.calls: true

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      cluster: HYSTRIX-CLUSTER

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 1s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
        ignoreExceptions:
          - de.springframework.monitoring.resilience4j.consumer.exceptions.BusinessException
    instances:
      personClient:
        baseConfig: default

  retry:
    configs:
      default:
        maxRetryAttempts: 2
        waitDuration: 100
        retryExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
        ignoreExceptions:
          - de.springframework.monitoring.resilience4j.consumer.exceptions.BusinessException
    instances:
      personClient:
        baseConfig: default

  bulkhead:
    configs:
      default:
        maxWaitDuration: 10ms
        maxConcurrentCalls: 20
    instances:
      personClient:
        baseConfig: default

  thread-pool-bulkhead:
    configs:
      default:
        maxThreadPoolSize: 4
        coreThreadPoolSize: 2
        queueCapacity: 2
    instances:
      personClient:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        eventConsumerBufferSize: 100
    instances:
      personClient:
        baseConfig: default
