logging:
  level:
    de.springframework.monitoring.resilience4j.consumer: INFO
    root: INFO

management:
  server:
    port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

server:
  port: 8080
