logging:
  level:
    de.springframework.monitoring.resilience4j.consumer: INFO
    root: INFO

management:
  server:
    port: 8090

server:
  port: 8080

producer:
  service:
    #url: http://localhost:8081
    url: http://resilience4j-producer-service
    path: /producer/api/v1
